/* ============================================================
 * Datei: service-worker.js
 * Zweck: PWA-Offline-Cache für Lernspiel
 * ============================================================ */
const CACHE_VERSION='ls-v1.0.0';const SHELL_CACHE=`shell-${CACHE_VERSION}`;const RUNTIME_CACHE=`runtime-${CACHE_VERSION}`;
const CORE_ASSETS=['./','./index.html','./manifest.webmanifest','./src/styles.css','./icon_32.png','./icon_64.png','./icon_128.png','./icon_256.png','./icon_512.png','./src/boot.js','./src/app.js','./src/router.js','./src/lib/storage.js','./src/auth/auth.js','./src/ui/Navbar.js','./src/ui/LoginForm.js','./src/ui/DashboardChild.js','./src/ui/DashboardParent.js','./src/ui/ExercisesList.js','./src/ui/ExercisePlay.js','./src/ui/StatsDetail.js','./src/ui/TrainHard.js','./src/ui/ProgressBook.js','./src/ui/MilestonePoster.js','./src/ui/SuperRun.js','./src/ui/NotFound.js','./src/data/exercises.js','./src/data/achievements.js','./src/data/goals.js','./offline.html'];
self.addEventListener('install',event=>event.waitUntil(caches.open(SHELL_CACHE).then(c=>c.addAll(CORE_ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.map(key=>![SHELL_CACHE,RUNTIME_CACHE].includes(key)?caches.delete(key):undefined))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{const{request}=event;if(request.mode==='navigate'){event.respondWith(fetch(request).then(resp=>{const x=resp.clone();caches.open(RUNTIME_CACHE).then(c=>c.put(request,x));return resp}).catch(async()=>{const c=await caches.open(RUNTIME_CACHE),x=await c.match(request);return x||caches.match('./offline.html')}));return}if(['script','style','worker'].includes(request.destination)){event.respondWith(caches.match(request).then(x=>x||fetch(request).then(resp=>{const y=resp.clone();caches.open(SHELL_CACHE).then(c=>c.put(request,y));return resp})));return}event.respondWith(caches.match(request).then(x=>x||fetch(request)))});
